### ISSUE TITLE
something is wrong when i run A2lParser(a2l_string)

### ISSUE THREAD

**Issue by acorn50** [Sauci/pya2l#13]
Traceback (most recent call last):
  File "E:/CanD/test.py", line 14, in <module>
    a2l = A2lParser(a2l_string)
  File "D:\python3.5\lib\site-packages\pya2l\parser\grammar\parser.py", line 163, in __init__
    self._yacc.parse(string)
  File "D:\python3.5\lib\site-packages\ply\yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "D:\python3.5\lib\site-packages\ply\yacc.py", line 1201, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "D:\python3.5\lib\site-packages\ply\yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
  File "D:\python3.5\lib\site-packages\pya2l\parser\grammar\parser.py", line 174, in p_error
    raise A2lFormatException('invalid sequence at position ', p.lexpos, string=p.lexer.lexdata)
pya2l.parser.grammar.parser.A2lFormatException: invalid sequence at position 58037
	..._ECU_ONLY                             INIT_SEGMENT 0x0                         /end PAGE                         /begin ADDRESS_MAPPING                             0xe0000                             0x40000400                             0

the error format in a2l  file as follow:

                       /begin PAGE
                            0x0 /* page number */
                            ECU_ACCESS_WITH_XCP_ONLY
                            XCP_READ_ACCESS_WITH_ECU_ONLY
                            XCP_WRITE_ACCESS_WITH_ECU_ONLY
                            INIT_SEGMENT 0x0
                        /end PAGE
                        /begin ADDRESS_MAPPING
                        0xe0000
                        0x40000400
                        0x21c
                        /end ADDRESS_MAPPING

**Comment by Sauci** [comment]
Hi,
Indeed, the ```INIT_SEGMENT``` property is missing in the grammar. I will add it.

**Comment by Sauci** [comment]
@acorn50 I updated the script (develop branch), could you confiirm that it works, and close this issue if it does?
Thanks

**Comment by acorn50** [comment]
I tried the develop branch, but the problem still exists.

**Comment by Sauci** [comment]
Are you sure it is the same error as the one you had previously? I added a test named ```test_if_data_memory_segment_segment_page_node``` in file **parser_test.py** which tests the missing optional ```INIT_SEGMENT``` property, could you confirm that you are able to parse the string named ```a2l_string``` defined in this function? Thanks for your feedback

**Comment by acorn50** [comment]
yes,same as the previous error, And the a2l file can be parsed in INCA. I parse the a2l file like this:

with open("config/test.a2l") as f:
    a2l_string = f.read()
    print(a2l_string)
    a2l = A2lParser(a2l_string)

**Comment by Sauci** [comment]
Have you tried to parse the following string:
```
         /begin PROJECT project_name "project long identifier"
             /begin MODULE first_module_name "first module long identifier"
                 /begin MOD_PAR "mod_par comment"
                     /begin MEMORY_SEGMENT
                         Dst80100000
                         ""
                         DATA
                         FLASH
                         INTERN
                         0x80100000
                         0x7FAE0
                         -1
                         -1
                         -1
                         -1
                         -1
                         /begin IF_DATA XCPplus 0x0102
                             /begin SEGMENT
                                 2       /* segment logical number */
                                 0x02       /* number of pages */
                                 0x00       /* address extension */
                                 0x00       /* compression method */
                                 0x00       /* encryption method */
                                 /begin PAGE
                                     0x00       /* page number */
                                     ECU_ACCESS_NOT_ALLOWED
                                     XCP_READ_ACCESS_NOT_ALLOWED
                                     XCP_WRITE_ACCESS_NOT_ALLOWED
                                 /end PAGE
                                 /begin PAGE
                                     0x01       /* page number */
                                     ECU_ACCESS_DONT_CARE
                                     XCP_READ_ACCESS_DONT_CARE
                                     XCP_WRITE_ACCESS_DONT_CARE
                                     INIT_SEGMENT 0xFE
                                 /end PAGE
                             /end SEGMENT
                         /end IF_DATA
                     /end MEMORY_SEGMENT
                 /end MOD_PAR
             /end MODULE
         /end PROJECT
```

If it works, it is an other problem you have (well, I have), otherwise, I guess something went wrong while updating the package. Could you tell me if this string raises an exception please?

**Comment by acorn50** [comment]
It works which you provide, but my doesn't work.When i delete the ADDRESS_MAPPING segment,it works.I think the problem is related to the ADDRESS_MAPPING segment.

**Comment by Sauci** [comment]
Ok, then it is an other issue. Could you provide the problematic a2l snippet and the call stack trace of the error please?

**Comment by acorn50** [comment]
/begin PAGE
                        0x0 /* page number */
                        ECU_ACCESS_WITH_XCP_ONLY
                        XCP_READ_ACCESS_WITH_ECU_ONLY
                        XCP_WRITE_ACCESS_WITH_ECU_ONLY
                        INIT_SEGMENT 0x0
                    /end PAGE
                    /begin ADDRESS_MAPPING
                    0xe0000
                    0x40000400
                    0x21c
                    /end ADDRESS_MAPPING 
when i delete ADDRESS_MAPPING segment,the error will be disappear,otherwisre the error same as the before.

**Comment by Sauci** [comment]
Understood, then I will have a look with your a2l snippet.
Could you open a new issue with the problematic snippet you mentionned? 
As you said, the problem arises on ```ADDRESS_MAPPING``` key, not on the ```INIT_SEGMENT```. Thus I will close this issue and work on the one you will open to keep a clear trace of the problems.

Thanks
