### ISSUE TITLE
AttributeError: 'Project' object has no attribute 'json'

### ISSUE THREAD

**Issue by eeyrw** [Sauci/pya2l#19]
I install pya2l directly via pip. The test code is copied from introduction. 
```
Traceback (most recent call last):
  File "pya2ltest.py", line 58, in <module>
    assert python_object_to_json_string(a2l.tree.project.json, sort_keys=True, indent=4) == """{
AttributeError: 'Project' object has no attribute 'json'
```

**Comment by Yanujz** [comment]
The same here

**Comment by Sauci** [comment]
Hello @eeyrw, @Yanujz, after a major update of the package, the feature is working now. You can dump the A2L to a JSON file, and even reload it from a JSON file. Please have a look at the test `test_a2l_to_json_command` [here](https://github.com/Sauci/pya2l/blob/develop/pya2l/cli_test.py), and the CLI implementation [here](https://github.com/Sauci/pya2l/blob/develop/pya2l/cli.py) for a more concrete example. I will now close this issue.

**Comment by eeyrw** [comment]
It's really a lot years of the issue and I am not working on A2L and related stuff and forget this completely...
