### ISSUE TITLE
error: invalid sequence with A2ML struct content where the "string"

### ISSUE THREAD

**Issue by kozmers** [Sauci/pya2l#2]
I got invalid sequence error when test the pya2l for my project's a2l file like below.
`from pya2l.parser import A2lParser as Parser

    a2l_string = """
    ASAP2_VERSION 1 60
        /begin PROJECT prj "PRJ"
            /begin MODULE DIM ""
                /begin A2ML
                    struct aaaa{
                        float;
                        taggedstruct{
                            block "BBBB" struct{
                                uchar;
                                taggedstruct{                              
                                    (block "C2222" struct{
                                        ulong;                            
                                    })*;
                                    (block "C3333" struct{
                                        taggedunion{
                                            "TEST";  ////////////// ERROR //////////A2lFormatException: invalid sequence
                                            "DDDD" struct{
                                                "TEST111" ulong;  ////////////// ERROR //////////A2lFormatException: invalid sequence
                                            };
                                        };
                                        taggedstruct{
                                           "TEST222" (ulong)*;  ////////////// ERROR //////////A2lFormatException: invalid sequence
                                        };
                                    })*;   
                                };
                            };
                        };
                    };
                /end A2ML
            /end MODULE
        /end PROJECT"""
    a2l = Parser(a2l_string)`

**Comment by kozmers** [comment]
`    block "FLASH" struct

      {

         taggedunion

         {                            /* ECU mode for copying RAM into Flash   */

              **"NOFLASHBACK";**   /// invalid sequence error

               **"AUTOFLASHBACK";**  /// invalid sequence error

            "TOOLFLASHBACK" struct

              {

               uint;                  /* routine number to copy RAM            */

                                      /* into flash (WP->RP)                   */

               taggedstruct

                {

                  "COPY_FRAME" (uchar)*; /* list of frames to be copied */

                };



               taggedunion

               {

                  "RequestRoutineResults" taggedstruct

                     {

                       "RNC_RESULT" (uchar)*;  /* result codes, that         */

                                               /* sign copy in progress      */

                     };

                  **"StartRoutine";**  /// invalid sequence error

                  **"CodedResult";**  /// invalid sequence error

               };

              };

         };

       };
`

**Comment by kozmers** [comment]
I add "a2ml_tag SEMICOLON " in  parser.py, and the error resolved :
`@staticmethod
    def p_a2ml_taggedunion_member(p):
        """a2ml_taggedunion_member : a2ml_tag SEMICOLON 
                                   | a2ml_tag a2ml_member SEMICOLON
                                   | a2ml_block_definition SEMICOLON"""`

**Comment by Sauci** [comment]
thanks for your feedback. I looked in the specification, and you are right, the 'tag semicolon' string is valid. I just pushed on the bugfix branch, could you give me a feedback please? thanks

**Comment by kozmers** [comment]
The bugfix branch fixed the problem. This issue can be closed.
I got another invalid sequence error with this:
` /begin MEMORY_SEGMENT Pst80080000 "" CODE FLASH INTERN 0x80080000 0x7FAE0 -1 -1 -1 -1 -1 



       /begin IF_DATA ETK_XETK

           /begin ETK_XETK_ACCESS

              SERIAL_INTERFACE

           /end ETK_XETK_ACCESS

       /end IF_DATA





     /end MEMORY_SEGMENT`

**Comment by kozmers** [comment]
The bugfix solved this problem. I got another issue, so, just close this and open another.
