### ISSUE TITLE
Release 0.0.9: File marked as suspicous by ESET Endpoint Antivirus

### ISSUE THREAD

**Issue by a543c23** [Sauci/pya2l#20]
Hello!

I just updated to release 0.0.9 and unfortunately, my virus scanner ESET Endpoint Antivirus deleted one dll as suspicious object:

﻿Time;Scanner;Object type;Object;Detection;Action;User;Information;Hash;First seen here
06/09/2023 14:14:33;Real-time file system protection;file;C:\Program Files\Python39\Lib\site-packages\pya2l\a2l_grpc\a2l_grpc_windows_amd64.dll;Suspicious Object;cleaned by deleting;;Event occurred on a new file created by the application: C:\Program Files\Python39\python.exe (46B758081313D2968A2E4293C6DDAB7DD25FBC0B).;9047E0CE705F52EDBC96215570904D129210247B;06/09/2023 14:14:24

**Comment by Sauci** [comment]
Hello,
Indeed, this package uses a shared library in the backend, due to the poor performances when using a pure Python parser. You can have a look at the source code [here](https://github.com/Sauci/a2l-grpc). So you could probably add an exception for it in your antivirus.
